"""Definitions"""
# General Constants

CONSTANTS = ("\n"
             "pitch = 0\n"
             "roll = 0\n"
             "yaw = 0\n"
             "alt = 0\n"
             "spd = 0\n"
             "thr = 0\n"
             "ws = [0,0]\n"
             "atp = 14.7 #ASL\n"
             "position = 0\n"
             "target = 0\n"
             "tgt_alt = 0\n"
             "anti = ''\n"
             "step = 0.25\n"
             "missile = ''\n"
             "wp_a = 0\n"
             "wp_a_alt = 0\n"
             "wp_b = 0\n"
             "wp_b_alt = 0\n"
             "wp_c = 0\n"
             "wp_c_alt = 0\n"
             "wp_d = 0\n"
             "wp_d_alt = 0\n")
